-- AlterTable
ALTER TABLE "Reviews" ALTER COLUMN "laborerRate" SET DEFAULT 0.0,
ALTER COLUMN "laborerRate" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Users" ALTER COLUMN "rate" SET DEFAULT 0.0,
ALTER COLUMN "rate" SET DATA TYPE DOUBLE PRECISION;
